// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



import "./globals.css";
import localFont from "next/font/local";

const funnelSans = localFont({
  src: [
    // {
    //   path: "fonts/funnel-sans/FunnelSans-Regular.ttf",
    //   weight: "400",
    //   style: "normal",
    // },
    {
      path: "fonts/funnel-sans/FunnelSans-Medium.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-funnel-sans",
  display: "swap",
});

export const metadata = {
  title: "Kislay Rai | Portfolio",
  description: "Portfolio showcasing my work and resume",
};

export default function RootLayout({ children }) {
  const theme = typeof window !== "undefined"
    ? localStorage.getItem("theme")
    : null;

  return (
    <html lang="en" className={theme === "dark" ? "dark" : ""}>
      <body className={`${funnelSans.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
