// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



import "./globals.css";
import { Space_Grotesk, JetBrains_Mono, Inter } from "next/font/google";

const displayFont = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const sansFont = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const monoFont = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata = {
  title: "Kislay Rai | Portfolio",
  description: "Portfolio showcasing my work and resume",
};

export default function RootLayout({ children }) {
  const theme = typeof window !== "undefined"
    ? localStorage.getItem("theme")
    : null;

  return (
    <html lang="en" className={theme === "dark" ? "dark" : ""}>
      <body
        className={`${sansFont.variable} ${displayFont.variable} ${monoFont.variable} font-sans antialiased bg-slate-100 dark:bg-[#0a0a0a] text-zinc-900 dark:text-zinc-300 min-h-screen selection:bg-pink-500/30 selection:text-pink-200 transition-colors duration-300`}
      >  {children}
      </body>
    </html>
  );
}
